# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Bananasplit-js CI Testing

on:
  push:
    branches: [ master ]
    
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 12.x ]

    env:
      NODE_ENV: test
      
      DB_DIALECT: mysql
      DB_HOST: localhost
      DB_PORT: 3306

      DB_DATABASE: test
      DB_USERNAME: root
      DB_PASSWORD: pass

    steps:
      - uses: actions/checkout@v2
        
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
        
      - run: npm ci

      - name: Install mysql2 driver
        run: npm i mysql2

      - name: Do migrations
        run: npx sequelize db:migrate

      - name: Seed the database
        run: npx sequelize db:seed

      - name: Test with jest
        run: npm test setup
    
    services:
      mysql:
        image: mysql:5.7
        env:
            MYSQL_ROOT_PASSWORD: pass
            MYSQL_DATABASE: test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
